module_online = "Online"

online_users = "%s Users Online"

##############
# Online Map #
##############
mt_online_map = "Online Map"
md_online_map = "Show the current online users with a map position."
