module_online = "Online"

online_users = "%s Users Online"
show_userlist = "Show online user list"
mt_online_online = "Online Users"
md_online_online = "Currently connected users."

##############
# Online Map #
##############
mt_online_map = "Online Map (%s)"
md_online_map = "Show the current online users with a map position."
